const emojiDictionary = {
  "😊": "Smiling",
  "❤️": "Love",
  "🏏": "Cricket Game",
  "🙈": "See-No-Evil Monkey",
  "👍": "Thumbs Up",
  "🏳️‍🌈": "Rainbow Flag",
  "🔥": "Fire",
  "🎂": "Birthday Cake",
  "🎸": "Guitar",
  "🤣": "Rolling on the Floor Laughing",
  "👀": "Eyes",
  "🙉": "Hear-No-Evil Monkey",
  "🙊": "Speak-No-Evil Monkey",
  "🍕": "Pizza",
  "🍺": "Beer Mug",
  "✈️": "Airplane",
  "💻": "Laptop",
  "📧": "E-Mail",
  "👎": "Thumbs Down",
  "🙏": "Folded Hands",
  "💋": "Kiss Mark",
  "🥡": "Takeout Box",
  "😳": "Disbelief",
  "😑": "Annoyance",
  "😔": "Sad",
};

export default emojiDictionary;
